name: ci

on: 
  push:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build, Tests, Cover, Pack and Publish (on push tag)
      shell: bash
      run: |
        dotnet tool install --global dotnet-releaser
        dotnet-releaser run --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml